### ISSUE TITLE
Projects Supported by The Network Steward Date?

### ISSUE THREAD

**Issue by vantwoutmaarten** [pkt-cash/ns-projects#79]

**Comment by vantwoutmaarten** [comment]
Hi guys,

I am wondering when will the network steward decide on which projects get funded.
Since my team and I are really eager to work on the project: PKT Wallet GUI with mining from your browser.

But it would be nice for us to plan ahead. 

Best Regards,
Maarten van 't Wout

**Comment by cjdelisle** [comment]
I've held off giving the news because one of our reviewers has not cast his vote, but since 4 our of 5 is enough that the decision is finalized anyway, I will provide the information in your pull request.
